import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'en' | 'de' | 'es' | 'fr' | 'hi' | 'mr' | 'ta';

export interface Language {
  code: LanguageCode;
  name: string;
}

export const languages: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'de', name: 'Deutsch' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'hi', name: 'हिन्दी (Hindi)' },
  { code: 'mr', name: 'मराठी (Marathi)' },
  { code: 'ta', name: 'தமிழ் (Tamil)' },
];

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navbar
    dashboard: 'Dashboard',
    familyFeed: 'Family Feed',
    sosHistory: 'SOS History',
    profile: 'Profile',
    logIn: 'Log In',
    register: 'Register',
    signOut: 'Sign Out',
    demoMode: 'DEMO MODE',
    
    // Landing
    systemOnline: 'Guardian Mesh System Online',
    tagline: '"One Tap Can Save a Life."',
    accessDashboard: 'Access Dashboard',
    systemFeatures: 'System Features',
    sosTitle: 'Emergency SOS',
    sosDesc: 'Trigger instant alert flags to your emergency contacts with one tap. Zero lag, high priority.',
    gpsTitle: 'Live GPS Tracking',
    gpsDesc: 'Captures high-accuracy browser coordinates and generates immediate Google Maps URLs.',
    familyTitle: 'Family Dashboard',
    familyDesc: 'Real-time Firestore snapshot synchronization alerts family members instantly.',
    historyTitle: 'Emergency History',
    historyDesc: 'Maintains a timeline log of all previous emergency coordinates.',
    futureTitle: 'Future Guardian Mesh Scope',
    futureDesc: 'The next phase of ResQVerse extends protection outside cellular and internet grids.',
    bluetoothTitle: 'Bluetooth Mesh Relay',
    bluetoothDesc: 'Relay SOS packets peer-to-peer across client devices without mobile network connectivity.',
    aiVoiceTitle: 'AI Voice Activated SOS',
    aiVoiceDesc: 'Continuous audio scanning triggers distress broadcasts on hearing voice stress triggers.',
    policeTitle: 'Local Law Enforcement',
    policeDesc: 'Direct encrypted websocket bridge with public safety answering points and police dispatch API.',
    termsOfService: 'Terms of Service',
    privacyFramework: 'Privacy Framework',
    developerNodeApi: 'Developer Node API',
    
    // Dashboard
    commandCenter: 'Guardian Command Center',
    statusSafe: 'SECURE / STANDBY',
    statusActive: 'BROADCAST ACTIVE',
    selectDistress: '1. Select distress profile',
    categoryDesc: 'Responders prepare based on medical, fire, accident, or threat profiles.',
    voiceSOS: 'Voice SOS Trigger',
    voiceActive: '🔴 Listening for voice triggers',
    voiceInactive: '⚪ Voice Trigger Standby',
    voiceNotSupported: 'Speech recognition not supported on this browser',
    holdSOS: 'SOS',
    standbyCommand: 'STANDBY FOR COMMAND',
    radarTitle: '2. Live Location Radar Sweep',
    radarStatus: 'RADAR ACTIVE',
    nodeDiagnostics: 'Node Diagnostics',
    deviceCell: 'Device Cell',
    batteryStatus: 'Battery Status',
    gpsPrecision: 'GPS Precision',
    latency: 'Latency',
    peerMesh: 'Peer Mesh',
    survivalGuide: 'Survival Guide',
    contactsTitle: 'Guardian Nodes (Contacts)',
    timelineLogs: 'Timeline Incident logs',
    verifyMaps: 'Verify Google Maps Telemetry',
    dialNode: 'Dial Node',
    welcome: 'Welcome',
    activeEmergency: 'ACTIVE EMERGENCY',
    safeButton: 'I am Safe Now',
    telemetryDetails: 'Telemetry Details',
    countdownOverlay: 'Broadcasting SOS',
    countdownSub: 'HOLD TO CANCEL - GEOLOCATION ACQUIRING',
    cancelDispatch: 'Cancel Dispatch',
    manageNodes: 'Manage Nodes',
    fullLog: 'Full Log',
    noticeHeader: 'Guardian mesh notice',
    noticeText: 'If cellular internet is absent, ResQVerse will compile coordinates into a structured SMS string for offline dispatch. Keep GPS enabled.',
    
    // SOS Success
    alertSent: 'Emergency Alert Sent Successfully',
    alertSentDesc: 'Guardian nodes notified. Active mapping link is synced in real-time on the Family Feed.',
    activeTelemetry: 'Active Telemetry Feed',
    guardianName: 'Guardian Name',
    timestamp: 'Broadcast Timestamp',
    gpsCoordinates: 'GPS Coordinates',
    nodeStatus: 'Node status',
    distressType: 'Distress Type',
    mapsLink: 'Google Maps Link',
    copyTelemetry: 'Copy SOS telemetry',
    copyTelemetryDone: 'Copied Log',
    resolvedNotice: 'Resolved the threat? Mark yourself safe to deactivate alarms across the Family Feed.',
    
    // Family Dashboard
    feedTitle: 'Guardian Mesh Feed',
    feedDesc: 'Real-time Firestore telemetry streaming active user distress parameters.',
    liveListener: 'Live Snapshot Listener Active',
    searchPlaceholder: 'Search User Nodes...',
    filterAll: 'All Feed',
    filterActive: '🔴 Active',
    filterSafe: '🟢 Safe',
    noReports: 'No matching reports found.',
    mapsTelemetry: 'Maps Telemetry',
    
    // Profile
    profileTitle: 'Guardian profile',
    profileDesc: 'Maintain medical telemetry status and active responder nodes.',
    personalInfo: 'Personal Information',
    fullName: 'Full Name',
    phone: 'Phone Number',
    bloodGroup: 'Blood Group',
    email: 'Email address',
    responderNodes: 'Guardian mesh responder nodes',
    editBtn: 'Edit Profile',
    cancelBtn: 'Cancel View',
    saveBtn: 'Save Configuration Changes',
    discard: 'Discard',
    medicalProfile: '1. Personal Medical Profile',
    networkNodes: 'Network nodes',
    bloodType: 'Blood type',
    
    // History
    logsTitle: 'Incident logs',
    logsDesc: 'Historical archive of all emergency signals emitted by this node.',
    emptyLogs: 'No emergency records logged.',
    telemetryId: 'Telemetry ID',
  },
  de: {
    // Navbar
    dashboard: 'Dashboard',
    familyFeed: 'Familien-Feed',
    sosHistory: 'SOS-Verlauf',
    profile: 'Profil',
    logIn: 'Einloggen',
    register: 'Registrieren',
    signOut: 'Abmelden',
    demoMode: 'DEMO-MODUS',
    
    // Landing
    systemOnline: 'Guardian Mesh System Online',
    tagline: '"Ein Klick kann ein Leben retten."',
    accessDashboard: 'Zum Dashboard',
    systemFeatures: 'Systemfunktionen',
    sosTitle: 'Notfall-SOS',
    sosDesc: 'Lösen Sie mit einem Fingertipp sofortige Alarmmeldungen an Ihre Notfallkontakte aus. Ohne Verzögerung.',
    gpsTitle: 'Live-GPS-Ortung',
    gpsDesc: 'Erfasst hochpräzise Browser-Koordinaten und generiert sofortige Google Maps-Links.',
    familyTitle: 'Familien-Dashboard',
    familyDesc: 'Die Echtzeit-Synchronisierung alarmiert Familienmitglieder sofort.',
    historyTitle: 'Notfallverlauf',
    historyDesc: 'Führt ein Verlaufsprotokoll aller vorherigen Notfallkoordinaten.',
    futureTitle: 'Zukünftiger Umfang von Guardian Mesh',
    futureDesc: 'Die nächste Phase von ResQVerse erweitert den Schutz außerhalb des Mobilfunknetzes.',
    bluetoothTitle: 'Bluetooth-Mesh-Relais',
    bluetoothDesc: 'SOS-Pakete Peer-to-Peer zwischen Client-Geräten ohne Mobilfunknetzverbindung weiterleiten.',
    aiVoiceTitle: 'KI-sprachaktiviertes SOS',
    aiVoiceDesc: 'Die kontinuierliche Audio-Abtastung löst Notrufe aus, wenn Notruf-Sprachbefehle erkannt werden.',
    policeTitle: 'Lokale Strafverfolgung',
    policeDesc: 'Direkte verschlüsselte Websocket-Brücke mit Rettungsleitstellen und Polizeiruf-Schnittstelle.',
    termsOfService: 'Nutzungsbedingungen',
    privacyFramework: 'Datenschutzrahmen',
    developerNodeApi: 'Entwickler-API',
    
    // Dashboard
    commandCenter: 'Notruf-Kontrollzentrum',
    statusSafe: 'SICHER / BEREITSCHAFT',
    statusActive: 'NOTRUF AKTIV',
    selectDistress: '1. Notfallprofil auswählen',
    categoryDesc: 'Helfer bereiten sich auf der Grundlage von medizinischen, Brand-, Unfall- oder Bedrohungsprofilen vor.',
    voiceSOS: 'Sprach-SOS-Auslöser',
    voiceActive: '🔴 Mikrofon aktiv für Notruf',
    voiceInactive: '⚪ Sprachauslöser im Standby',
    voiceNotSupported: 'Spracherkennung wird von diesem Browser nicht unterstützt',
    holdSOS: 'SOS',
    standbyCommand: 'BEREITSCHAFT FÜR NOTRUF',
    radarTitle: '2. Live-Radarortung',
    radarStatus: 'RADAR AKTIV',
    nodeDiagnostics: 'Knoten-Diagnose',
    deviceCell: 'Geräte-Akku',
    batteryStatus: 'Akkustand',
    gpsPrecision: 'GPS-Genauigkeit',
    latency: 'Latenz',
    peerMesh: 'Mesh-Partner',
    survivalGuide: 'Überlebenshilfe',
    contactsTitle: 'Schutzkontakte (Guardian Nodes)',
    timelineLogs: 'Ereignisprotokolle',
    verifyMaps: 'Google Maps Telemetrie prüfen',
    dialNode: 'Anrufen',
    welcome: 'Willkommen',
    activeEmergency: 'AKTIVER NOTFALL',
    safeButton: 'Ich bin in Sicherheit',
    telemetryDetails: 'Telemetriedetails',
    countdownOverlay: 'SOS wird gesendet',
    countdownSub: 'ABBRECHEN HALTEN - GEOLOKALISIERUNG WIRD ERFASST',
    cancelDispatch: 'Notruf abbrechen',
    manageNodes: 'Kontakte verwalten',
    fullLog: 'Ganzes Protokoll',
    noticeHeader: 'Guardian-Mesh-Hinweis',
    noticeText: 'Wenn kein Internet verfügbar ist, kompiliert ResQVerse Koordinaten in eine strukturierte SMS für den Offline-Versand. GPS aktiv lassen.',
    
    // SOS Success
    alertSent: 'Notruf erfolgreich gesendet',
    alertSentDesc: 'Notfallkontakte wurden benachrichtigt. Der Live-Standortlink wird in Echtzeit im Familien-Feed synchronisiert.',
    activeTelemetry: 'Aktiver Telemetrie-Feed',
    guardianName: 'Name des Absenders',
    timestamp: 'Zeitstempel des Notrufs',
    gpsCoordinates: 'GPS-Koordinaten',
    nodeStatus: 'Knotenstatus',
    distressType: 'Notfallkategorie',
    mapsLink: 'Google Maps Link',
    copyTelemetry: 'SOS-Telemetrie kopieren',
    copyTelemetryDone: 'Protokoll kopiert',
    resolvedNotice: 'Gefahr vorbei? Melden Sie sich als sicher, um Alarme im Familien-Feed zu deaktivieren.',
    
    // Family Dashboard
    feedTitle: 'Guardian Mesh Feed',
    feedDesc: 'Echtzeit-Notrufe und Telemetriedaten von Netzwerkmitgliedern.',
    liveListener: 'Live-Listener aktiv',
    searchPlaceholder: 'Netzwerkknoten suchen...',
    filterAll: 'Alle Feeds',
    filterActive: '🔴 Aktiv',
    filterSafe: '🟢 Sicher',
    noReports: 'Keine entsprechenden Notrufe gefunden.',
    mapsTelemetry: 'Karten-Ortung',
    
    // Profile
    profileTitle: 'Schutzprofil',
    profileDesc: 'Verwalten Sie medizinische Daten und aktive Empfängerkontakte.',
    personalInfo: 'Persönliche Daten',
    fullName: 'Vollständiger Name',
    phone: 'Telefonnummer',
    bloodGroup: 'Blutgruppe',
    email: 'E-Mail-Adresse',
    responderNodes: 'Zugeordnete Schutzempfänger',
    editBtn: 'Profil bearbeiten',
    cancelBtn: 'Ansicht verlassen',
    saveBtn: 'Änderungen speichern',
    discard: 'Verwerfen',
    medicalProfile: '1. Medizinisches Profil',
    networkNodes: 'Netzwerkknoten',
    bloodType: 'Blutgruppe',
    
    // History
    logsTitle: 'Ereignisprotokoll',
    logsDesc: 'Verlauf aller von diesem Gerät gesendeten Notsignale.',
    emptyLogs: 'Keine Notrufprotokolle vorhanden.',
    telemetryId: 'Telemetrie-ID',
  },
  es: {
    // Navbar
    dashboard: 'Panel',
    familyFeed: 'Red Familiar',
    sosHistory: 'Historial SOS',
    profile: 'Perfil',
    logIn: 'Iniciar Sesión',
    register: 'Registrarse',
    signOut: 'Cerrar Sesión',
    demoMode: 'MODO DEMO',
    
    // Landing
    systemOnline: 'Sistema Guardian Mesh en Línea',
    tagline: '"Un toque puede salvar una vida."',
    accessDashboard: 'Acceder al Panel',
    systemFeatures: 'Características',
    sosTitle: 'SOS de Emergencia',
    sosDesc: 'Active alertas instantáneas para sus contactos de emergencia con un toque. Sin demoras.',
    gpsTitle: 'Seguimiento GPS en Vivo',
    gpsDesc: 'Captura coordenadas precisas del navegador y genera enlaces de Google Maps de inmediato.',
    familyTitle: 'Panel Familiar',
    familyDesc: 'Sincronización en tiempo real que alerta a la familia al instante cuando hay peligro.',
    historyTitle: 'Historial de Emergencias',
    historyDesc: 'Mantiene un registro temporal de todas las coordenadas de emergencias anteriores.',
    futureTitle: 'Alcance Futuro de Guardian Mesh',
    futureDesc: 'La próxima fase amplía la protección fuera de las redes móviles e internet.',
    bluetoothTitle: 'Relé de Red Bluetooth',
    bluetoothDesc: 'Transmisión de paquetes SOS de dispositivo a dispositivo sin señal de telefonía.',
    aiVoiceTitle: 'SOS Activado por Voz IA',
    aiVoiceDesc: 'Monitoreo de audio local para emitir alertas al detectar palabras clave de auxilio.',
    policeTitle: 'Enlace con la Policía',
    policeDesc: 'Conexión directa encriptada con los centros de despacho policial y API de rescate.',
    termsOfService: 'Términos de Servicio',
    privacyFramework: 'Políticas de Privacidad',
    developerNodeApi: 'API para Desarrolladores',
    
    // Dashboard
    commandCenter: 'Centro de Comando Guardian',
    statusSafe: 'SEGURO / EN ESPERA',
    statusActive: 'TRANSMISIÓN SOS ACTIVA',
    selectDistress: '1. Seleccione perfil de auxilio',
    categoryDesc: 'Los equipos se preparan según el perfil: médico, incendio, accidente o amenaza.',
    voiceSOS: 'Activación por Voz SOS',
    voiceActive: '🔴 Micrófono activo para auxilio',
    voiceInactive: '⚪ Activación de voz en espera',
    voiceNotSupported: 'Reconocimiento de voz no soportado en este navegador',
    holdSOS: 'SOS',
    standbyCommand: 'EN ESPERA DE COMANDO',
    radarTitle: '2. Escaneo de Radar de Ubicación',
    radarStatus: 'RADAR ACTIVO',
    nodeDiagnostics: 'Diagnósticos del Nodo',
    deviceCell: 'Batería del Móvil',
    batteryStatus: 'Estado de Batería',
    gpsPrecision: 'Precisión GPS',
    latency: 'Latencia',
    peerMesh: 'Nodos Cercanos',
    survivalGuide: 'Guía de Supervivencia',
    contactsTitle: 'Nodos Protectores (Contactos)',
    timelineLogs: 'Registros de Incidentes',
    verifyMaps: 'Verificar Telemetría en Google Maps',
    dialNode: 'Llamar Nodo',
    welcome: 'Bienvenido',
    activeEmergency: 'EMERGENCIA ACTIVA',
    safeButton: 'Estoy a Salvo',
    telemetryDetails: 'Detalles de Telemetría',
    countdownOverlay: 'Transmitiendo SOS',
    countdownSub: 'MANTENGA PRESIONADO PARA CANCELAR - ADQUIRIENDO GPS',
    cancelDispatch: 'Cancelar Envío',
    manageNodes: 'Gestionar Nodos',
    fullLog: 'Registro Completo',
    noticeHeader: 'Aviso de Guardian Mesh',
    noticeText: 'Si no hay internet, ResQVerse compilará las coordenadas en un SMS estructurado para despacho offline. Mantenga el GPS activo.',
    
    // SOS Success
    alertSent: 'Alerta de Emergencia Enviada',
    alertSentDesc: 'Contactos notificados. El enlace de ubicación en vivo se sincroniza en tiempo real en la Red Familiar.',
    activeTelemetry: 'Flujo de Telemetría Activo',
    guardianName: 'Nombre del Emisor',
    timestamp: 'Hora del Envío',
    gpsCoordinates: 'Coordenadas GPS',
    nodeStatus: 'Estado del Nodo',
    distressType: 'Tipo de Auxilio',
    mapsLink: 'Enlace de Google Maps',
    copyTelemetry: 'Copiar Telemetría SOS',
    copyTelemetryDone: 'Copiado',
    resolvedNotice: '¿Peligro resuelto? Indique que está a salvo para desactivar las alarmas en la Red Familiar.',
    
    // Family Dashboard
    feedTitle: 'Red Familiar de Guardian Mesh',
    feedDesc: 'Telemetría en tiempo real y flujo de alertas de los miembros de la red.',
    liveListener: 'Listener en tiempo real activo',
    searchPlaceholder: 'Buscar nodos de usuarios...',
    filterAll: 'Todo el Feed',
    filterActive: '🔴 Activos',
    filterSafe: '🟢 A Salvo',
    noReports: 'No se encontraron alertas coincidentes.',
    mapsTelemetry: 'Telemetría de Mapas',
    
    // Profile
    profileTitle: 'Perfil del Guardián',
    profileDesc: 'Mantenga sus datos médicos y contactos de respuesta activos.',
    personalInfo: 'Información Personal',
    fullName: 'Nombre Completo',
    phone: 'Número de Teléfono',
    bloodGroup: 'Grupo Sanguíneo',
    email: 'Correo Electrónico',
    responderNodes: 'Contactos del Nodo Familiar',
    editBtn: 'Editar Perfil',
    cancelBtn: 'Cancelar Edición',
    saveBtn: 'Guardar Configuración',
    discard: 'Descartar',
    medicalProfile: '1. Perfil Médico Personal',
    networkNodes: 'Nodos en Red',
    bloodType: 'Grupo Sanguíneo',
    
    // History
    logsTitle: 'Registro de Incidentes',
    logsDesc: 'Archivo histórico de todas las señales de auxilio emitidas por este nodo.',
    emptyLogs: 'No hay incidentes registrados.',
    telemetryId: 'ID de Telemetría',
  },
  fr: {
    // Navbar
    dashboard: 'Tableau',
    familyFeed: 'Flux Familial',
    sosHistory: 'Historique SOS',
    profile: 'Profil',
    logIn: 'Connexion',
    register: 'S\'inscrire',
    signOut: 'Déconnexion',
    demoMode: 'MODE DÉMO',
    
    // Landing
    systemOnline: 'Système Guardian Mesh en Ligne',
    tagline: '"Un clic peut sauver une vie."',
    accessDashboard: 'Accéder au Tableau',
    systemFeatures: 'Fonctionnalités',
    sosTitle: 'SOS Urgence',
    sosDesc: 'Déclenchez des alertes immédiates vers vos contacts d\'urgence en un clic. Sans délai.',
    gpsTitle: 'Localisation GPS en Direct',
    gpsDesc: 'Capture les coordonnées précises du navigateur et génère des liens Google Maps instantanés.',
    familyTitle: 'Réseau Familial',
    familyDesc: 'Synchronisation en temps réel qui alerte instantanément les membres de la famille.',
    historyTitle: 'Historique des SOS',
    historyDesc: 'Conserve un registre temporel de toutes les coordonnées des urgences passées.',
    futureTitle: 'Portée Future du Guardian Mesh',
    futureDesc: 'La prochaine phase étend la protection en dehors des réseaux cellulaires et d\'internet.',
    bluetoothTitle: 'Relais Réseau Bluetooth',
    bluetoothDesc: 'Relais de paquets SOS de smartphone à smartphone sans connexion réseau mobile.',
    aiVoiceTitle: 'SOS Activé par Voix IA',
    aiVoiceDesc: 'Écoute audio locale pour déclencher une alerte lors de la détection de mots clés d\'urgence.',
    policeTitle: 'Lien Forces de l\'Ordre',
    policeDesc: 'Connexion directe chiffrée avec les services de secours et API d\'intervention.',
    termsOfService: 'Conditions d\'utilisation',
    privacyFramework: 'Confidentialité',
    developerNodeApi: 'API Développeurs',
    
    // Dashboard
    commandCenter: 'Centre de Contrôle Guardian',
    statusSafe: 'SÉCURISÉ / EN ATTENTE',
    statusActive: 'DIFFUSION SOS ACTIVE',
    selectDistress: '1. Sélectionnez un profil d\'urgence',
    categoryDesc: 'Les secours se préparent selon le profil: médical, incendie, accident ou menace.',
    voiceSOS: 'Déclencheur SOS Vocal',
    voiceActive: '🔴 Micro actif pour détection',
    voiceInactive: '⚪ Déclencheur vocal en attente',
    voiceNotSupported: 'Reconnaissance vocale non supportée sur ce navigateur',
    holdSOS: 'SOS',
    standbyCommand: 'EN ATTENTE DE COMMANDE',
    radarTitle: '2. Balayage Radar de Position',
    radarStatus: 'RADAR ACTIF',
    nodeDiagnostics: 'Diagnostics du Nœud',
    deviceCell: 'Batterie Mobile',
    batteryStatus: 'Niveau de Batterie',
    gpsPrecision: 'Précision GPS',
    latency: 'Latence',
    peerMesh: 'Nœuds Relais',
    survivalGuide: 'Guide de Survie',
    contactsTitle: 'Nœuds Protecteurs (Contacts)',
    timelineLogs: 'Registres d\'Incidents',
    verifyMaps: 'Vérifier la position sur Google Maps',
    dialNode: 'Appeler Nœud',
    welcome: 'Bienvenue',
    activeEmergency: 'URGENCE ACTIVE',
    safeButton: 'Je suis en sécurité',
    telemetryDetails: 'Détails de la Télémétrie',
    countdownOverlay: 'Envoi du SOS en cours',
    countdownSub: 'MAINTENIR POUR ANNULER - ACQUISITION GPS',
    cancelDispatch: 'Annuler l\'envoi',
    manageNodes: 'Gérer les Nœuds',
    fullLog: 'Registre Complet',
    noticeHeader: 'Notice Guardian Mesh',
    noticeText: 'Si internet est absent, ResQVerse compilera les coordonnées dans un SMS structuré pour envoi hors ligne. Gardez le GPS actif.',
    
    // SOS Success
    alertSent: 'Alerte d\'Urgence Envoyée',
    alertSentDesc: 'Contacts notifiés. Le lien de position en direct est synchronisé en temps réel sur le Flux Familial.',
    activeTelemetry: 'Flux Télémétrique Actif',
    guardianName: 'Nom de l\'Émetteur',
    timestamp: 'Heure de l\'Envoi',
    gpsCoordinates: 'Coordonnées GPS',
    nodeStatus: 'Statut du Nœud',
    distressType: 'Type d\'Urgence',
    mapsLink: 'Lien Google Maps',
    copyTelemetry: 'Copier la Télémétrie',
    copyTelemetryDone: 'Copié',
    resolvedNotice: 'Danger écarté? Signalez que vous êtes en sécurité pour désactiver les alarmes sur le Flux Familial.',
    
    // Family Dashboard
    feedTitle: 'Flux Familial Guardian Mesh',
    feedDesc: 'Télémétrie en temps réel et alertes des membres du réseau.',
    liveListener: 'Écoute en temps réel active',
    searchPlaceholder: 'Rechercher des nœuds...',
    filterAll: 'Tous les Flux',
    filterActive: '🔴 Actifs',
    filterSafe: '🟢 En Sécurité',
    noReports: 'Aucune alerte correspondante trouvée.',
    mapsTelemetry: 'Télémétrie Cartographique',
    
    // Profile
    profileTitle: 'Profil du Gardien',
    profileDesc: 'Gérez vos données médicales et vos contacts d\'urgence actifs.',
    personalInfo: 'Informations Personnelles',
    fullName: 'Nom Complet',
    phone: 'Numéro de Téléphone',
    bloodGroup: 'Groupe Sanguin',
    email: 'Adresse E-mail',
    responderNodes: 'Contacts d\'Urgence Rattachés',
    editBtn: 'Modifier le Profil',
    cancelBtn: 'Annuler l\'Édition',
    saveBtn: 'Enregistrer les Modifications',
    discard: 'Abandonner',
    medicalProfile: '1. Profil Médical Personnel',
    networkNodes: 'Nœuds Réseau',
    bloodType: 'Groupe Sanguin',
    
    // History
    logsTitle: 'Registre d\'Incidents',
    logsDesc: 'Historique de tous les signaux d\'urgence émis par ce nœud.',
    emptyLogs: 'Aucun incident enregistré.',
    telemetryId: 'ID Télémétrie',
  },
  hi: {
    // Navbar
    dashboard: 'डैशबोर्ड',
    familyFeed: 'पारिवारिक फीड',
    sosHistory: 'एसओएस इतिहास',
    profile: 'प्रोफ़ाइल',
    logIn: 'लॉग इन',
    register: 'रजिस्टर',
    signOut: 'लॉग आउट',
    demoMode: 'डेमो मोड',
    
    // Landing
    systemOnline: 'गार्डियन मेश सिस्टम सक्रिय है',
    tagline: '"एक टैप जीवन बचा सकता है।🏽"',
    accessDashboard: 'डैशबोर्ड खोलें',
    systemFeatures: 'सिस्टम विशेषताएं',
    sosTitle: 'आपातकालीन एसओएस',
    sosDesc: 'एक टैप से अपने आपातकालीन संपर्कों को तुरंत अलर्ट भेजें। बिना किसी देरी के।',
    gpsTitle: 'लाइव जीपीएस ट्रैकिंग',
    gpsDesc: 'उच्च सटीकता के साथ आपके स्थान के निर्देशांक प्राप्त करता है और तत्काल Google मानचित्र लिंक बनाता है।',
    familyTitle: 'पारिवारिक डैशबोर्ड',
    familyDesc: 'रीयल-टाइम फायरस्टोर सिंक खतरे के समय परिवार के सदस्यों को तुरंत सचेत करता है।',
    historyTitle: 'आपातकालीन इतिहास',
    historyDesc: 'सभी पिछले आपातकालीन अलर्ट और निर्देशांकों का इतिहास रखता है।',
    futureTitle: 'भविष्य की सुरक्षा योजनाएं',
    futureDesc: 'रेसक्यूवर्स का अगला चरण बिना मोबाइल नेटवर्क के भी सुरक्षा प्रदान करेगा।',
    bluetoothTitle: 'ब्लूटूथ मेश रिले',
    bluetoothDesc: 'बिना मोबाइल नेटवर्क के एक फोन से दूसरे फोन में आपातकालीन संदेश पहुंचाना।',
    aiVoiceTitle: 'एआई वॉयस एक्टिवेटेड एसओएस',
    aiVoiceDesc: 'संकट के शब्द (जैसे "बचाओ") सुनने पर अपने आप आपातकालीन संदेश भेजना।',
    policeTitle: 'पुलिस विभाग से एकीकरण',
    policeDesc: 'स्थानीय पुलिस आपातकालीन प्रतिक्रिया टीमों और जीपीएस डिस्पैच एपीआई से सीधा जुड़ाव।',
    termsOfService: 'सेवा की शर्तें',
    privacyFramework: 'गोपनीयता नीति',
    developerNodeApi: 'डेवलपर नोड एपीआई',
    
    // Dashboard
    commandCenter: 'गार्डियन कंट्रोल सेंटर',
    statusSafe: 'सुरक्षित / स्टैंडबाय',
    statusActive: 'आपातकालीन अलर्ट सक्रिय है',
    selectDistress: '1. आपातकाल का प्रकार चुनें',
    categoryDesc: 'सहायक टीमें चिकित्सा, आग, दुर्घटना या सुरक्षा संकट के अनुसार तैयारी करती हैं।',
    voiceSOS: 'आवाज अलर्ट एक्टिवेटर',
    voiceActive: '🔴 आवाज अलर्ट के लिए माइक ऑन है',
    voiceInactive: '⚪ आवाज अलर्ट बंद है',
    voiceNotSupported: 'यह ब्राउज़र आवाज पहचान का समर्थन नहीं करता है',
    holdSOS: 'एसओएस (SOS)',
    standbyCommand: 'आदेश के लिए तैयार',
    radarTitle: '2. लाइव लोकेशन राडार स्कैन',
    radarStatus: 'राडार सक्रिय है',
    nodeDiagnostics: 'सिस्टम डायग्नोस्टिक्स',
    deviceCell: 'फोन बैटरी',
    batteryStatus: 'बैटरी चार्ज',
    gpsPrecision: 'जीपीएस सटीकता',
    latency: 'नेटवर्क देरी',
    peerMesh: 'समीप नोड्स',
    survivalGuide: 'सुरक्षा मार्गदर्शिका',
    contactsTitle: 'गार्डियन नोड्स (आपातकालीन संपर्क)',
    timelineLogs: 'घटना लॉग इतिहास',
    verifyMaps: 'Google मानचित्र पर स्थान देखें',
    dialNode: 'कॉल करें',
    welcome: 'स्वागत है',
    activeEmergency: 'सक्रिय आपातकाल',
    safeButton: 'मैं सुरक्षित हूँ',
    telemetryDetails: 'स्थान विवरण (टेलीमेट्री)',
    countdownOverlay: 'एसओएस अलर्ट भेजा जा रहा है',
    countdownSub: 'रद्द करने के लिए दबाकर रखें - जीपीएस खोजा जा रहा है',
    cancelDispatch: 'अलर्ट रद्द करें',
    manageNodes: 'संपर्क प्रबंधित करें',
    fullLog: 'पूरा इतिहास',
    noticeHeader: 'नोड सुरक्षा सूचना',
    noticeText: 'इंटरनेट न होने पर रेसक्यूवर्स ऑफलाइन भेजने के लिए निर्देशांक को एक एसएमएस में संकलित करेगा। जीपीएस चालू रखें।',
    
    // SOS Success
    alertSent: 'आपातकालीन अलर्ट सफलतापूर्वक भेजा गया',
    alertSentDesc: 'आपातकालीन संपर्कों को सूचित कर दिया गया है। लाइव लोकेशन लिंक पारिवारिक फीड पर रीयल-टाइम में उपलब्ध है।',
    activeTelemetry: 'सक्रिय टेलीमेट्री फीड',
    guardianName: 'भेजने वाले का नाम',
    timestamp: 'अलर्ट भेजने का समय',
    gpsCoordinates: 'जीपीएस निर्देशांक',
    nodeStatus: 'नोड स्थिति',
    distressType: 'संकट का प्रकार',
    mapsLink: 'Google मानचित्र लिंक',
    copyTelemetry: 'विवरण कॉपी करें',
    copyTelemetryDone: 'कॉपी किया गया',
    resolvedNotice: 'खतरा टल गया? पारिवारिक फीड पर अलार्म बंद करने के लिए खुद को सुरक्षित घोषित करें।',
    
    // Family Dashboard
    feedTitle: 'गार्डियन मेश फीड (लाइव)',
    feedDesc: 'नेटवर्क सदस्यों से लाइव आपातकालीन अलर्ट और स्थान विवरण।',
    liveListener: 'रीयल-टाइम मॉनिटर सक्रिय है',
    searchPlaceholder: 'सदस्यों को खोजें...',
    filterAll: 'सभी फीड',
    filterActive: '🔴 सक्रिय संकट',
    filterSafe: '🟢 सुरक्षित',
    noReports: 'कोई मिलान अलर्ट नहीं मिला।',
    mapsTelemetry: 'मानचित्र पर देखें',
    
    // Profile
    profileTitle: 'गार्डियन प्रोफ़ाइल',
    profileDesc: 'अपनी चिकित्सा जानकारी और आपातकालीन संपर्क विवरण अपडेट रखें।',
    personalInfo: 'व्यक्तिगत जानकारी',
    fullName: 'पूरा नाम',
    phone: 'मोबाइल नंबर',
    bloodGroup: 'रक्त समूह (ब्लड ग्रुप)',
    email: 'ईमेल पता',
    responderNodes: 'आपातकालीन संपर्क (गार्डियन नोड्स)',
    editBtn: 'प्रोफ़ाइल बदलें',
    cancelBtn: 'रद्द करें',
    saveBtn: 'जानकारी सुरक्षित करें',
    discard: 'खारिज करें',
    medicalProfile: '1. व्यक्तिगत चिकित्सा प्रोफ़ाइल',
    networkNodes: 'नेटवर्क नोड्स',
    bloodType: 'रक्त समूह',
    
    // History
    logsTitle: 'घटना लॉग इतिहास',
    logsDesc: 'इस नोड से भेजे गए सभी आपातकालीन सिग्नलों का इतिहास।',
    emptyLogs: 'कोई आपातकालीन घटना दर्ज नहीं है।',
    telemetryId: 'टेलीमेट्री आईडी',
  },
  mr: {
    // Navbar
    dashboard: 'डॅशबोर्ड',
    familyFeed: 'कौटुंबिक फीड',
    sosHistory: 'SOS इतिहास',
    profile: 'प्रोफाइल',
    logIn: 'लॉग इन',
    register: 'नोंदणी',
    signOut: 'लॉग आउट',
    demoMode: 'डेमो मोड',
    
    // Landing
    systemOnline: 'गार्डियन मेश यंत्रणा सक्रिय',
    tagline: '"एक टॅप वाचवू शकतो जीव."',
    accessDashboard: 'डॅशबोर्ड उघडा',
    systemFeatures: 'यंत्रणेची वैशिष्ट्ये',
    sosTitle: 'तात्काळ SOS',
    sosDesc: 'एक टॅपसह तुमच्या आपत्कालीन संपर्कांना त्वरित धोक्याचा इशारा पाठवा.',
    gpsTitle: 'लाईव्ह GPS ट्रॅकिंग',
    gpsDesc: 'अचूक जीपीएस स्थान मिळवून तात्काळ गुगल मॅप्स लिंक तयार करते.',
    familyTitle: 'कौटुंबिक डॅशबोर्ड',
    familyDesc: 'धोक्याच्या वेळी कुटुंबातील सदस्यांना त्वरित इशारा देणारे रीयल-टाइम अपडेट्स.',
    historyTitle: 'आपत्कालीन इतिहास',
    historyDesc: 'सर्व मागील धोक्याच्या इशाऱ्यांचे आणि स्थानांचे रेकॉर्ड्स ठेवते.',
    futureTitle: 'भविष्यातील सुरक्षा व्याप्ती',
    futureDesc: 'रेसक्यूवर्सचा पुढील टप्पा मोबाईल नेटवर्क नसतानाही सुरक्षा देईल.',
    bluetoothTitle: 'ब्लूटूथ मेश रिले',
    bluetoothDesc: 'मोबाईल नेटवर्कशिवाय फोन-टू-फोन आपत्कालीन संदेश पाठवणे.',
    aiVoiceTitle: 'AI आवाज सक्रिय SOS',
    aiVoiceDesc: 'संकटकालीन आवाज (उदा. "मदत करा") ऐकल्यावर स्वयंचलित संदेश पाठवणे.',
    policeTitle: 'पोलीस यंत्रणेशी जोडणी',
    policeDesc: 'स्थानिक पोलीस नियंत्रण कक्ष आणि जीपीएस प्रणालीशी थेट जोडणी.',
    termsOfService: 'वापराच्या अटी',
    privacyFramework: 'गोपनीयता धोरण',
    developerNodeApi: 'डेव्हलपर API',
    
    // Dashboard
    commandCenter: 'गार्डियन नियंत्रण कक्ष',
    statusSafe: 'सुरक्षित / स्टँडबाय',
    statusActive: 'धोक्याचा इशारा सुरू आहे',
    selectDistress: '१. आपत्कालीन प्रकार निवडा',
    categoryDesc: 'मदत गट वैद्यकीय, आग, अपघात किंवा सुरक्षा संकटानुसार तयारी करतात.',
    voiceSOS: 'आवाज सक्रियता',
    voiceActive: '🔴 आवाज इशाऱ्यासाठी माईक सुरू आहे',
    voiceInactive: '⚪ आवाज इशारा बंद आहे',
    voiceNotSupported: 'हे ब्राऊझर आवाज ओळखण्यास समर्थन देत नाही',
    holdSOS: 'SOS',
    standbyCommand: 'आदेशासाठी सज्ज',
    radarTitle: '२. लाईव्ह लोकेशन रडार स्कॅन',
    radarStatus: 'रडार सुरू आहे',
    nodeDiagnostics: 'यंत्रणा तपासणी',
    deviceCell: 'फोन बॅटरी',
    batteryStatus: 'बॅटरी चार्ज',
    gpsPrecision: 'GPS अचूकता',
    latency: 'नेटवर्क विलंब',
    peerMesh: 'जवळपासचे नोड्स',
    survivalGuide: 'सुरक्षा मार्गदर्शक',
    contactsTitle: 'आपत्कालीन संपर्क (गार्डियन नोड्स)',
    timelineLogs: 'घटना लॉग इतिहास',
    verifyMaps: 'गुगल मॅपवर स्थान पहा',
    dialNode: 'कॉल करा',
    welcome: 'स्वागत आहे',
    activeEmergency: 'सक्रिय आपत्कालीन संकट',
    safeButton: 'मी सुरक्षित आहे',
    telemetryDetails: 'टेलीमेट्री तपशील (स्थान)',
    countdownOverlay: 'धोक्याचा इशारा पाठवला जात आहे',
    countdownSub: 'रद्द करण्यासाठी दाबून ठेवा - GPS शोधत आहे',
    cancelDispatch: 'इशारा रद्द करा',
    manageNodes: 'संपर्क व्यवस्थापित करा',
    fullLog: 'पूर्ण इतिहास',
    noticeHeader: 'सुरक्षा नोड नोटीस',
    noticeText: 'इंटरनेट नसल्यास ऑफलाइन वितरणासाठी रेसक्यूवर्स स्थान माहिती एका SMS मध्ये संकलित करेल. GPS सुरू ठेवा.',
    
    // SOS Success
    alertSent: 'आपत्कालीन इशारा यशस्वीरीत्या पाठवला',
    alertSentDesc: 'आपत्कालीन संपर्कांना कळवले आहे. लाईव्ह स्थान लिंक कौटुंबिक फीडवर तात्काळ उपलब्ध आहे.',
    activeTelemetry: 'सक्रिय टेलीमेट्री फीड',
    guardianName: 'पाठवणाऱ्याचे नाव',
    timestamp: 'इशारा पाठवण्याची वेळ',
    gpsCoordinates: 'GPS निर्देशांक',
    nodeStatus: 'नोड स्थिती',
    distressType: 'संकटाचा प्रकार',
    mapsLink: 'गुगल मॅप्स लिंक',
    copyTelemetry: 'तपशील कॉपी करा',
    copyTelemetryDone: 'कॉपी केले',
    resolvedNotice: 'धोका टळला? कौटुंबिक फीडवरील अलार्म बंद करण्यासाठी स्वतःला सुरक्षित घोषित करा.',
    
    // Family Dashboard
    feedTitle: 'गार्डियन मेश फीड (लाईव्ह)',
    feedDesc: 'नेटवर्क सदस्यांकडून लाईव्ह आपत्कालीन अलर्ट आणि स्थान तपशील.',
    liveListener: 'रीयल-टाइम नियंत्रण सुरू आहे',
    searchPlaceholder: 'सदस्य शोधा...',
    filterAll: 'सर्व फीड',
    filterActive: '🔴 सक्रिय धोके',
    filterSafe: '🟢 सुरक्षित',
    noReports: 'कोणतेही जुळणारे अलर्ट सापडले नाहीत.',
    mapsTelemetry: 'मॅपवर पहा',
    
    // Profile
    profileTitle: 'गार्डियन प्रोफाइल',
    profileDesc: 'वैद्यकीय माहिती आणि आपत्कालीन संपर्क तपशील अद्ययावत ठेवा.',
    personalInfo: 'वैयक्तिक माहिती',
    fullName: 'पूर्ण नाव',
    phone: 'मोबाईल नंबर',
    bloodGroup: 'रक्त गट (ब्लड ग्रुप)',
    email: 'ईमेल पत्ता',
    responderNodes: 'आपत्कालीन संपर्क (गार्डियन नोड्स)',
    editBtn: 'प्रोफाइल बदला',
    cancelBtn: 'रद्द करा',
    saveBtn: 'माहिती जतन करा',
    discard: 'रद्द करा',
    medicalProfile: '१. वैयक्तिक वैद्यकीय प्रोफाइल',
    networkNodes: 'नेटवर्क नोड्स',
    bloodType: 'रक्त गट',
    
    // History
    logsTitle: 'आपत्कालीन घटना लॉग',
    logsDesc: 'या फोनवरून पाठवलेल्या सर्व आपत्कालीन सिग्नल्सचा इतिहास.',
    emptyLogs: 'कोणतीही आपत्कालीन घटना नोंदवली नाही.',
    telemetryId: 'टेलीमेट्री आयडी',
  },
  ta: {
    // Navbar
    dashboard: 'டாஷ்போர்டு',
    familyFeed: 'குடும்பக் குழு',
    sosHistory: 'SOS வரலாறு',
    profile: 'சுயவிவரம்',
    logIn: 'உள்நுழைக',
    register: 'பதிவுசெய்க',
    signOut: 'வெளியேறு',
    demoMode: 'டெமோ பயன்முறை',
    
    // Landing
    systemOnline: 'கார்டியன் மெஷ் அமைப்பு ஆன்லைனில் உள்ளது',
    tagline: '"ஒரு தட்டல் உயிரைக் காப்பாற்றும்."',
    accessDashboard: 'டாஷ்போர்டை அணுகவும்',
    systemFeatures: 'அம்சங்கள்',
    sosTitle: 'அவசரகால SOS',
    sosDesc: 'ஒரே தட்டலில் உங்களது அவசரகால தொடர்புகளுக்கு உடனடி எச்சரிக்கை சமிக்ஞையை அனுப்புங்கள்.',
    gpsTitle: 'நேரடி ஜிபிஎஸ் கண்காணிப்பு',
    gpsDesc: 'துல்லியமான ஜிபிஎஸ் இருப்பிடத்தைப் பெற்று உடனடி கூகுள் மேப்ஸ் இணைப்பை உருவாக்குகிறது.',
    familyTitle: 'குடும்ப டாஷ்போர்டு',
    familyDesc: 'ஆபத்து நேரத்தில் குடும்ப உறுப்பினர்களை உடனடியாக எச்சரிக்கும் நேரடி புதுப்பிப்புகள்.',
    historyTitle: 'அவசரகால வரலாறு',
    historyDesc: 'அனைத்து முந்தைய அவசரகால எச்சரிக்கைகளின் இருப்பிட விவரங்களைச் சேமிக்கிறது.',
    futureTitle: 'எதிர்கால கார்டியன் மெஷ் நோக்கம்',
    futureDesc: 'மொபைல் நெட்வொர்க் இல்லாதபோதும் ரெஸ்க்யூவெர்ஸ் பாதுகாப்பு வழங்கும்.',
    bluetoothTitle: 'ப்ளூடூத் மெஷ் ரிலே',
    bluetoothDesc: 'மொபைல் நெட்வொர்க் இல்லாமல் ஒரு போனில் இருந்து மற்றொரு போனுக்கு செய்தி அனுப்புதல்.',
    aiVoiceTitle: 'AI குரல் மூலம் SOS',
    aiVoiceDesc: 'ஆபத்தான குரல் (उदा. "காப்பாத்துங்க") கேட்கும்போது தானியங்கி செய்தி அனுப்புதல்.',
    policeTitle: 'காவல்துறை இணைப்பு',
    policeDesc: 'உள்ளூர் காவல் கட்டுப்பாட்டு அறை மற்றும் ஜிபிஎஸ் அமைப்புகளுடன் நேரடி இணைப்பு.',
    termsOfService: 'விதிமுறைகள்',
    privacyFramework: 'தனியுரிமைக் கொள்கை',
    developerNodeApi: 'டெவலப்பர் API',
    
    // Dashboard
    commandCenter: 'கார்டியன் கட்டுப்பாட்டு மையம்',
    statusSafe: 'பாதுகாப்பானது / காத்திருப்பு',
    statusActive: 'ஆபத்து எச்சரிக்கை செயலில் உள்ளது',
    selectDistress: '1. அவசர வகையைத் தேர்ந்தெடுக்கவும்',
    categoryDesc: 'உதவிக் குழுக்கள் மருத்துவம், தீ, விபத்து அல்லது பாதுகாப்பு அச்சுறுத்தலுக்கு ஏற்பத் தயாராகின்றன.',
    voiceSOS: 'குரல் எச்சரிக்கை',
    voiceActive: '🔴 குரல் எச்சரிக்கைக்கு மைக் ஆன் செய்யப்பட்டுள்ளது',
    voiceInactive: '⚪ குரல் எச்சரிக்கை முடக்கப்பட்டுள்ளது',
    voiceNotSupported: 'இந்த உலாவி குரல் அங்கீகாரத்தை ஆதரிக்கவில்லை',
    holdSOS: 'SOS',
    standbyCommand: 'கட்டளைக்குத் தயார்',
    radarTitle: '2. நேரடி ரேடார் கண்காணிப்பு',
    radarStatus: 'ரேடார் செயலில் உள்ளது',
    nodeDiagnostics: 'அமைப்பு கண்டறிதல்',
    deviceCell: 'பேட்டரி நிலை',
    batteryStatus: 'பேட்டரி சார்ஜ்',
    gpsPrecision: 'ஜிபிஎஸ் துல்லியம்',
    latency: 'நெட்வொர்க் தாமதம்',
    peerMesh: 'நெருங்கிய நோடுகள்',
    survivalGuide: 'பாதுகாப்பு கையேடு',
    contactsTitle: 'அவசரகால தொடர்புகள் (கார்டியன் நோடுகள்)',
    timelineLogs: 'சம்பவ பதிவுகள்',
    verifyMaps: 'கூகுள் மேப்பில் இருப்பிடத்தைப் பார்',
    dialNode: 'அழைப்பு செய்',
    welcome: 'வரவேற்கிறோம்',
    activeEmergency: 'செயலில் உள்ள அவசரநிலை',
    safeButton: 'நான் பாதுகாப்பாக இருக்கிறேன்',
    telemetryDetails: 'இருப்பிட விவரங்கள் (டெலிமெட்ரி)',
    countdownOverlay: 'ஆபத்து எச்சரிக்கை அனுப்பப்படுகிறது',
    countdownSub: 'ரத்து செய்ய அழுத்திப் பிடிக்கவும் - ஜிபிஎஸ் தேடுகிறது',
    cancelDispatch: 'எச்சரிக்கையை ரத்துசெய்',
    manageNodes: 'தொடர்புகளை நிர்வகி',
    fullLog: 'முழு வரலாறு',
    noticeHeader: 'பாதுகாப்பு அறிவிப்பு',
    noticeText: 'இணையம் இல்லாதபோது ஆஃப்லைனில் அனுப்ப இருப்பிடத்தை ஒரு எஸ்எம்எஸ்-ஆக ரெஸ்க்யூவெர்ஸ் தொகுக்கும். ஜிபிஎஸ் ஆன்-இல் வைக்கவும்.',
    
    // SOS Success
    alertSent: 'அவசரகால எச்சரிக்கை வெற்றிகரமாக அனுப்பப்பட்டது',
    alertSentDesc: 'அவசரகால தொடர்புகளுக்கு அறிவிக்கப்பட்டுள்ளது. நேரடி இருப்பிட இணைப்பு குடும்பப் பக்கத்தில் கிடைக்கிறது.',
    activeTelemetry: 'செயலில் உள்ள டெலிமெட்री ஃபீட்',
    guardianName: 'அனுப்பியவரின் பெயர்',
    timestamp: 'அனுப்பிய நேரம்',
    gpsCoordinates: 'ஜிபிஎஸ் ஒருங்கிணைப்புகள்',
    nodeStatus: 'கார்டியன் நிலை',
    distressType: 'சம்பவ வகை',
    mapsLink: 'கூகுள் மேப்ஸ் இணைப்பு',
    copyTelemetry: 'விவரங்களை நகலெடு',
    copyTelemetryDone: 'நகலெடுக்கப்பட்டது',
    resolvedNotice: 'ஆபத்து நீங்கியதா? குடும்பப் பக்கத்தில் அலாரத்தை நிறுத்த உங்களைப் பாதுகாப்பானவர் என்று அறிவிக்கவும்.',
    
    // Family Dashboard
    feedTitle: 'கார்டியன் மெஷ் ஃபீட் (நேரடி)',
    feedDesc: 'கார்டியன் உறுப்பினர்களிடமிருந்து நேரடி அவசரகால எச்சரிக்கைகள் மற்றும் இருப்பிட விவரங்கள்.',
    liveListener: 'நேரடி கண்காணிப்பு செயலில் உள்ளது',
    searchPlaceholder: 'உறுப்பினர்களைத் தேடுங்கள்...',
    filterAll: 'அனைத்து ஃபீட்',
    filterActive: '🔴 செயலில் உள்ள ஆபத்துகள்',
    filterSafe: '🟢 பாதுகாப்பானது',
    noReports: 'எச்சரிக்கைகள் எதுவும் காணப்படவில்லை.',
    mapsTelemetry: 'வரைபடத்தில் பார்',
    
    // Profile
    profileTitle: 'கார்டியன் சுயவிவரம்',
    profileDesc: 'உங்கள் மருத்துவ மற்றும் அவசரகால தொடர்பு விவரங்களை புதுப்பித்து வைக்கவும்.',
    personalInfo: 'தனிப்பட்ட தகவல்',
    fullName: 'முழு பெயர்',
    phone: 'கைபேசி எண்',
    bloodGroup: 'இரத்த வகை (பிளட் குரூப்)',
    email: 'மின்னஞ்சல் முகவரி',
    responderNodes: 'கார்டியன் நோடுகள் (அவசரகால தொடர்புகள்)',
    editBtn: 'சுயவிவரத்தைத் திருத்து',
    cancelBtn: 'ரத்துசெய்',
    saveBtn: 'தகவலைச் சேமி',
    discard: 'ரத்துசெய்',
    medicalProfile: '1. தனிப்பட்ட மருத்துவ சுயவிவரம்',
    networkNodes: 'நெட்வொர்க் நோடுகள்',
    bloodType: 'இரத்த வகை',
    
    // History
    logsTitle: 'சம்பவங்களின் வரலாறு',
    logsDesc: 'இந்த நோடில் இருந்து அனுப்பப்பட்ட அனைத்து அவசர சமிக்ஞைகளின் வரலாறு.',
    emptyLogs: 'அவசரகால சம்பவங்கள் எதுவும் பதிவு செய்யப்படவில்லை.',
    telemetryId: 'டெலிமெட்ரி ஐடி',
  }
};

interface LanguageContextType {
  currentLanguage: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('resqverse_lang');
    if (saved && Object.keys(translations).includes(saved)) {
      return saved as LanguageCode;
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('resqverse_lang', lang);
  };

  const t = (key: string): string => {
    const dictionary = translations[currentLanguage] || translations['en'];
    return dictionary[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
